### ISSUE TITLE
Ignoring "auto-play lone option" setting

### ISSUE THREAD

**Issue by jeffXvX** [Graham-Hayes/AC-Ink-Integration#4]
The AC conversation game object has a checkbox for "Auto-play lone option"
The AC-Ink-Integration ignores this setting and always autoplays when there is one lone option left. 
Your documentation suggests that "Auto-selection lone option" would be a field in "Third Party Ink Script Action" but there is no such field.

As a work-around, I went to ActionInkRunScript.cs line 248 and disabled the code which always selects the lone option automatically. I would suggest as a fix to read the boolean variable called "autoplay" from AC and execute according to the user preference.

Thanks

**Comment by Graham-Hayes** [comment]
Thanks, in my own project I had to do the same, I’ll get it on the main this weekend!

**Comment by Graham-Hayes** [comment]
Feature added.
