### ISSUE TITLE
Update for 1.78+ Adventure Creator API changes

### ISSUE THREAD

**Issue by cidneyhamilton** [Graham-Hayes/AC-Ink-Integration#6]
Installing this plugin on the latest version of Adventure Creator will result in the following errors:

```
Assets/AC-Ink Integration/ACInkIntegration.cs(35,41): error CS0123: No overload for 'AfterLoad' matches delegate 'EventManager.Delegate_SaveID'
Assets/AC-Ink Integration/ACInkIntegration.cs(43,41): error CS0123: No overload for 'AfterLoad' matches delegate 'EventManager.Delegate_SaveID'
```

It looks like EventManager.OnFinishLoading now requires passing an integer saveID; it should be easy enough to update the method signature to get this working with the latest version.

**Comment by Graham-Hayes** [comment]
Thanks!
